//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADON
    {
        public string MAHD { get; set; }
        public Nullable<decimal> TIENDV { get; set; }
        public Nullable<int> SLGHEMUA { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
        public string MAKM { get; set; }
    }
}
