//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public string MAHD { get; set; }
        public string MAKH { get; set; }
        public string MAPHIM { get; set; }
        public Nullable<System.DateTime> NGAYLAPHD { get; set; }
        public string SUATCHIEU { get; set; }
        public Nullable<int> SLGHEMUA { get; set; }
        public string THANHTIEN { get; set; }
    
        public virtual PHIM PHIM { get; set; }
        public virtual PHIM PHIM1 { get; set; }
    }
}
