//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHCHIEU
    {
        public string MALICHCHIEU { get; set; }
        public string MAPHIM { get; set; }
        public Nullable<int> THOILUONG { get; set; }
        public string GIOCHIEU { get; set; }
        public Nullable<System.DateTime> NGAYCHIEU { get; set; }
        public string LOAICHIEU { get; set; }
        public string MARAP { get; set; }
        public string GIA { get; set; }
    
        public virtual PHIM PHIM { get; set; }
        public virtual RAP RAP { get; set; }
    }
}
