//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public string MAKH { get; set; }
        public string MAPHIM { get; set; }
        public Nullable<System.DateTime> NGAYLAPHD { get; set; }
        public string MAHD { get; set; }
    }
}
