//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIM
    {
        public string MAPHIM { get; set; }
        public string TENPHIM { get; set; }
        public Nullable<int> NAMSX { get; set; }
        public string MATL { get; set; }
        public Nullable<System.DateTime> NgayKhoiChieu { get; set; }
        public string Daodien { get; set; }
        public string QuocGia { get; set; }
    }
}
